In [8]:
import pandas as pd

In [11]:
df = pd.read_html('https://gist.github.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6')[0]

In [12]:
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,NaN,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,NaN,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,NaN,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,NaN,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,NaN,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,NaN,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,NaN,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,NaN,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,NaN,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [13]:
coluna = df['Name']

In [14]:
coluna = df[['Name', 'Type 1', 'Attack']]

In [15]:
linhas = df[df['Attack'] > 100]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   #           800 non-null    int64
 2   Name        800 non-null    object
 3   Type 1      800 non-null    object
 4   Type 2      414 non-null    object
 5   Total       800 non-null    int64
 6   HP          800 non-null    int64
 7   Attack      800 non-null    int64
 8   Defense     800 non-null    int64
 9   Sp. Atk     800 non-null    int64
 10  Sp. Def     800 non-null    int64
 11  Speed       800 non-null    int64
 12  Generation  800 non-null    int64
 13  Legendary   800 non-null    bool
dtypes: bool(1), float64(1), int64(9), object(3)
memory usage: 82.2+ KB

In [17]:
df.tail()

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,NaN,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,NaN,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,NaN,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,NaN,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,NaN,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [18]:
df.shape

(800, 14)

In [19]:
df [(df['Attack'] >= 80) & (df['Defense'] >= 150)]

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
98,NaN,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
223,NaN,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False
224,NaN,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
268,NaN,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
332,NaN,306,Aggron,Steel,Rock,530,70,110,180,60,60,50,3,False
333,NaN,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
413,NaN,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
414,NaN,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
424,NaN,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
749,NaN,680,Doublade,Steel,Ghost,448,59,110,150,45,49,35,6,False
789,NaN,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False
795,NaN,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True

In [20]:
df ["Indice de força"] = df['Attack'] + df['Defense'] + df['Speed']

In [21]:
df.sort_values(by = "Indice de força", ascending=False)

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Indice de força
424,NaN,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True,430
333,NaN,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False,420
163,NaN,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,420
413,NaN,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False,405
409,NaN,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False,395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,NaN,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False,75
187,NaN,173,Cleffa,Fairy,NaN,218,50,25,28,45,55,15,2,False,68
188,NaN,174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False,60
121,NaN,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False,60
488,NaN,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False,40

In [22]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})

In [26]:
linha = df.iloc[1]

In [27]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [34]:
print(linha)

A    3
B    6
C    9
Name: 2, dtype: int64

In [29]:
linhas = df.iloc[[0, 2]]

print(linhas)

   A  B  C
0  1  4  7
2  3  6  9

In [31]:
valor = df.iloc[1, 0]

print(valor)

2

In [33]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}, index=['a','b','c'])

In [ ]:
linha = df.loc['b']

print(linha)

In [35]:
df

   A  B  C
a  1  4  7
b  2  5  8
c  3  6  9

In [36]:
linhas = df.loc[['a', 'c']]

print(linhas)

   A  B  C
a  1  4  7
c  3  6  9

In [37]:
linhas = df.loc[df['A'] > 1]

print(linhas)

   A  B  C
b  2  5  8
c  3  6  9

In [38]:
df

   A  B  C
a  1  4  7
b  2  5  8
c  3  6  9

In [39]:
df = pd.read_excel('meu_arquivo.xlsx')

In [40]:
df

    Nome  Idade       Sexo
0   João     21  Masculino
1  Maria     18   Feminino
2  Pedro     34  Masculino
3  Joana     25   Feminino

In [41]:
tabela_wiki = pd.read_html('https://en.wikipedia.org/wiki/Minnesota')

In [45]:
tabela_wiki_temperatura = pd.read_html('https://en.wikipedia.org/wiki/Minnesota', match='Average daily maximum and minimum temperatures for selected cities in Minnesota')

In [46]:
tabela_wiki_temperatura[0]

              Location July (°F) July (°C) January (°F) January (°C)
0          Minneapolis     83/64     28/18         23/7       −4/−13
1           Saint Paul     83/63     28/17         23/6       −5/−14
2            Rochester     82/63     28/17         23/3       −5/−16
3               Duluth     76/55     24/13         19/1       −7/−17
4            St. Cloud     81/58     27/14        18/−1       −7/−18
5              Mankato     86/62     30/16         23/3       −5/−16
6  International Falls     77/52     25/11        15/−6       −9/−21

In [47]:
dados = [[1, 'João', 'São Paulo'], [2, 'Maria', 'Rio de Janeiro'], [3, 'José', 'Belo Horizonte']]

df = pd.DataFrame(dados, columns=['id', 'nome', 'cidade'])

In [48]:
df

   id   nome          cidade
0   1   João       São Paulo
1   2  Maria  Rio de Janeiro
2   3   José  Belo Horizonte

In [49]:
dados = [{'id': 1, 'nome': 'João', 'cidade': 'São Paulo'}, {'id': 2,
'nome': 'Maria', 'cidade': 'Rio de Janeiro'}, {'id': 3, 'nome': 'José', 'cidade': 'Belo Horizonte'}]

df = pd.DataFrame(dados)

In [50]:
df.head()

   id   nome          cidade
0   1   João       São Paulo
1   2  Maria  Rio de Janeiro
2   3   José  Belo Horizonte