In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('meu_arquivo.csv', encoding='Latin1', sep=';')

In [9]:
df

    Nome  Idade       Sexo
0   João     21  Masculino
1  Maria     18   Feminino
2  Pedro     34  Masculino
3  Joana     25   Feminino

In [10]:
df.head()

    Nome  Idade       Sexo
0   João     21  Masculino
1  Maria     18   Feminino
2  Pedro     34  Masculino
3  Joana     25   Feminino

In [11]:
df.head(2)

    Nome  Idade       Sexo
0   João     21  Masculino
1  Maria     18   Feminino

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    4 non-null      object
 1   Idade   4 non-null      int64
 2   Sexo    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.shape

(4, 3)

In [18]:
print(f'O DataFrame contém {df.shape[0]} linhas e {df.shape[1]} colunas ')

O DataFrame contém 4 linhas e 3 colunas

_____________________________________________________________________________________________

In [23]:
personagens_df = pd.DataFrame({
    'nome': ['Luke Skywalker', 'Yoda', 'Palpatine'],
    'idade': [13,1000,70],
    'peso': [70.5,  15.2, 60.5],
    'É jedi': [True, True, False]

})

In [24]:
personagens_df

             nome  idade  peso  É jedi
0  Luke Skywalker     13  70.5    True
1            Yoda   1000  15.2    True
2       Palpatine     70  60.5   False

In [25]:
personagens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    3 non-null      object
 1   idade   3 non-null      int64
 2   peso    3 non-null      float64
 3   É jedi  3 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 203.0+ bytes

In [26]:
personagens_df.columns

Index(['nome', 'idade', 'peso', 'É jedi'], dtype='object')

In [28]:
from sqlalchemy.sql.expression import column
personagens_df_renomeado = personagens_df.rename(columns={
    'nome': 'Nome Completo',
    'idade': 'Idade Aproximada'
})

In [29]:
personagens_df_renomeado

    Nome Completo  Idade Aproximada  peso  É jedi
0  Luke Skywalker                13  70.5    True
1            Yoda              1000  15.2    True
2       Palpatine                70  60.5   False

In [30]:
personagens_df

             nome  idade  peso  É jedi
0  Luke Skywalker     13  70.5    True
1            Yoda   1000  15.2    True
2       Palpatine     70  60.5   False

In [33]:
personagens_df.columns = ['NOME', 'IDADE', 'PESO', 'É Jedi']

In [34]:
personagens_df

             NOME  IDADE  PESO  É Jedi
0  Luke Skywalker     13  70.5    True
1            Yoda   1000  15.2    True
2       Palpatine     70  60.5   False

In [36]:
data = pd.read_csv('GasPricesinBrazil_2004-2019.csv', sep = ';')

In [37]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [38]:
data.columns

Index(['Unnamed: 0', 'DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO',
       'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO', 'MÊS',
       'ANO'],
      dtype='object')

In [39]:
data['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

Posição dos estados de acordo com length.

In [46]:
data.iloc[400]

Unnamed: 0                                    400
DATA INICIAL                           2004-08-15
DATA FINAL                             2004-08-21
REGIÃO                                    SUDESTE
ESTADO                             RIO DE JANEIRO
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  969
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.359
DESVIO PADRÃO REVENDA                       0.145
PREÇO MÍNIMO REVENDA                        1.029
PREÇO MÁXIMO REVENDA                        1.799
MARGEM MÉDIA REVENDA                        0.205
COEF DE VARIAÇÃO REVENDA                    0.107
PREÇO MÉDIO DISTRIBUIÇÃO                    1.154
DESVIO PADRÃO DISTRIBUIÇÃO                  0.174
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5444
PREÇO MÁXIMO DISTRIBUIÇÃO                  1.4976
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.151
MÊS                                             8
ANO                                          2004
Name: 400, dtype: object